language: ruby
script: "bundle exec rspec spec/"

rvm:
  - 2.1
  - 2.2
  - ruby-head

before_install:
  - gem update --system
  - gem update bundler

install: bundle install --jobs=1 --retry=3

matrix:
  allow_failures:
    - rvm: ruby-head

